# Generated by Django 5.1.6 on 2025-03-20 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0002_rename_dados_dadosboletim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Janeiro', 'Janeiro'), ('Feveireiro', 'Feveireiro'), ('Marco', 'Março'), ('Abril', 'Abril'), ('Maio', 'Maio'), ('Junho', 'Junho'), ('Julho', 'Julho'), ('Agosto', 'Agosto'), ('Setembro', 'Setembro'), ('Outubro', 'Outubro'), ('Novembro', 'Novembro'), ('Dezembro', 'Dezembro')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='dadosboletim',
            name='mes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ocorrencias.mes'),
        ),
    ]
