# Generated by Django 5.1.6 on 2025-03-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0003_mes_alter_dadosboletim_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mes',
            name='nome',
            field=models.CharField(choices=[('Janeiro', 'Janeiro'), ('Feveireiro', 'Feveireiro'), ('Marco', 'Marco'), ('Abril', 'Abril'), ('Maio', 'Maio'), ('Junho', 'Junho'), ('Julho', 'Julho'), ('Agosto', 'Agosto'), ('Setembro', 'Setembro'), ('Outubro', 'Outubro'), ('Novembro', 'Novembro'), ('Dezembro', 'Dezembro')], max_length=20),
        ),
    ]
